groups:
  - name: nobl9-bot
    rules:
      - alert: HighErrorRate
        expr: rate(nobl9_bot_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High error rate detected
          description: "Error rate is {{ $value }} per second"

      - alert: HighResponseTime
        expr: nobl9_bot_response_time_seconds > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High response time detected
          description: "Response time is {{ $value }} seconds"

      - alert: TooManyActiveConversations
        expr: nobl9_bot_active_conversations > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Too many active conversations
          description: "{{ $value }} active conversations"

      - alert: LowCommandRate
        expr: rate(nobl9_bot_commands_total[5m]) < 0.1
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: Low command rate detected
          description: "Command rate is {{ $value }} per second" 